# WARNING: Some settings require nightly fmt.
# Execute with:
#     cargo +nighthly fmt
blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
brace_style = "AlwaysNextLine"
chain_width = 50
color = "Always"
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
edition = "2021"
enum_discrim_align_threshold = 50
fn_call_width = 80
fn_single_line = false
force_multiline_blocks = false
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
indent_style = "Visual"
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
max_width = 120
newline_style = "Unix"
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = false
short_array_element_width_threshold = 40
single_line_if_else_max_width = 50
struct_field_align_threshold = 50
struct_lit_single_line = true
struct_lit_width = 40
struct_variant_width = 40
trailing_comma = "Vertical"
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true